import os
import json
import tkinter as tk
from concurrent.futures import ThreadPoolExecutor
import asyncio
import threading
from Image_Sequence_Scenes import Image_sequence_generation

try:
    from PIL import Image, ImageTk 
    HAS_PIL = True 
except ImportError:
    HAS_PIL = False

from tkinter import ttk, messagebox



# Paths defined based on requirements
BASE_DIR = r"D:\AI_Schemea"
IMAGE_DIR = os.path.join(BASE_DIR, "IMAGE")
JSON_FILE = os.path.join(BASE_DIR, "Text_Files", "processed_output.json")

MAX_WORKERS = 4   # how many parallel threads (image + video jobs combined)

# -- Parse input JSON text into Individual parts

def process_scenes(json_input):

    # Convert string → JSON if necessary
    if isinstance(json_input, str):
        data = json.loads(json_input)
    else:
        data = json_input

    scene_visuals = []
    scene_animations = []
    scene_text = []
    vo_lines = []
    scene_vo_lines = []
    scene_durations = []
    historical_photos = []

    for item in data:

        scene = item.get("scene")

        primary_visual = item.get("primary_visual_image")
        animation = item.get("animation")
        negative_animation = item.get("negative_video_prompt")
        historical_photo = item.get("historical_photo", False)
        ref_visual = item.get("reference_visual")
        print("NIGAAAAAAAAAAA:  ", scene, primary_visual, historical_photo, ref_visual)


        if historical_photo is True or ref_visual is not None:
            primary_visual = None
        

        if primary_visual is None and historical_photo is False and ref_visual is not None:
            import urllib.request
            import os
            
            ext = os.path.splitext(ref_visual.split('?')[0])[-1]
            if not ext or ext == ".png":
                ext = ".jpg"
            
            
                
            filename = f"scene{scene}_reference{ext}"
            save_path = os.path.join(IMAGE_DIR, filename)
            
            try:
                req = urllib.request.Request(ref_visual, headers={'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'})
                with urllib.request.urlopen(req) as response, open(save_path, 'wb') as out_file:
                    out_file.write(response.read())
                print(f"[INFO] Downloaded reference visual for scene {scene} to {save_path}")
            except Exception as e:
                print(f"[ERROR] Failed to download reference visual for scene {scene}: {e}")
                
            # Skip adding to scene_visuals so it's not generated by Flux
            # We can still add it with a null prompt if we want it preserved in output
            scene_visuals.append({
                "scene": scene,
                "primary_visual_image": None
            })

        elif primary_visual is None and ref_visual is None and historical_photo is True:
            def blank_function():
                pass
            blank_function()
            scene_visuals.append({
                "scene": scene,
                "primary_visual_image": None
            })
            
        else:
            # Scene + primary visual
            scene_visuals.append({
                "scene": scene,
                "primary_visual_image": primary_visual
            })

        if primary_visual is None:
            animation = None
            negative_animation = None


        # Scene + animation
        scene_animations.append({
            "scene": scene,
            "animation": animation,
            "negative_video_prompt": negative_animation
        })

        # Scene + text
        scene_text.append({
            "scene": scene,
            "small": item.get("on_screen_text_small"),
            "bold": item.get("on_screen_text_bold"),
            "large": item.get("on_screen_text_large")
        })

        # Collect VO lines
        if item.get("vo_line"):
            vo_lines.append(item["vo_line"])
            
        scene_vo_lines.append({
            "scene": scene,
            "vo_line": item.get("vo_line")
        })

        scene_durations.append({
            "scene": scene,
            "duration_seconds": item.get("duration_seconds")
        })

        # Historical photos
        if item.get("historical_photo") is True:
            historical_photos.append({
                "scene": scene,
                "historical_photo_description": item.get("historical_photo_description"),
                "vo_line": item.get("vo_line", ""),
                "duration_seconds": item.get("duration_seconds", "")
            })

    # Combine VO lines into one string
    combined_vo = " ".join(vo_lines)

    return {
        "scene_visuals": scene_visuals,
        "scene_animations": scene_animations,
        "scene_text": scene_text,
        "vo_script": combined_vo,
        "scene_vo_lines": scene_vo_lines,
        "scene_durations": scene_durations,
        "historical_photos": historical_photos
    }

# -----------------------------------------------------------------------------

# ── Load JSON File for PARSING ────────────────────────────────────────────────
def Json_File_Parsing():
    with open("D:\AI_Schemea\Text_Files\processed_output.json", "r", encoding="utf-8") as file:
        data = json.load(file)

    # EXTRACT Image Prompts from file
    Image_prompts=[]
    scene_animations = {str(item.get("scene", "")): item.get("animation") for item in data.get("scene_animations", [])}
    
    for item in data.get("scene_visuals", []):
        prompt = item.get("primary_visual_image")
        scene_id_str = str(item.get("scene", ""))
        anim = scene_animations.get(scene_id_str)
        
        # Skip if prompt is null or if animation is null
        if prompt and anim:
            Image_prompts.append({
                "scene": item["scene"],
                "prompt": prompt
            })
    
    return Image_prompts
# ──────────────────────────────────────────────────────────────────────────────


class CorporateUIApp(tk.Tk):
    def __init__(self, on_ready_callback=None):
        super().__init__()
        self.on_ready_callback = on_ready_callback
        self.title("AI Visualizer - Corporate Edition")
        self.geometry("1400x900")

        # Simple Corporate UI Styling (Dark Theme)
        self.configure(bg="#1E1E1E")
        self.style = ttk.Style(self)
        try:
            self.style.theme_use("clam")
        except tk.TclError:
            pass
            
        self.style.configure("TFrame", background="#1E1E1E")
        self.style.configure("Card.TFrame", background="#2D2D30", borderwidth=1, relief="solid")
        self.style.configure("Sidebar.TFrame", background="#252526", borderwidth=0)
        self.style.configure("TLabel", background="#1E1E1E", foreground="#CCCCCC", font=("Segoe UI", 11))
        self.style.configure("Header.TLabel", font=("Segoe UI", 18, "bold"), foreground="#FFFFFF", background="#1E1E1E")
        self.style.configure("SidebarHeader.TLabel", font=("Segoe UI", 14, "bold"), foreground="#FFFFFF", background="#252526")
        self.style.configure("Sidebar.TLabel", background="#252526", foreground="#CCCCCC", font=("Segoe UI", 11))
        self.style.configure("TButton", font=("Segoe UI", 11, "bold"), padding=8, background="#0E639C", foreground="#FFFFFF")
        self.style.map("TButton", background=[("active", "#1177BB")])
        self.style.configure("Danger.TButton", background="#C53A3A", foreground="#FFFFFF")
        self.style.map("Danger.TButton", background=[("active", "#E54A4A")])
        # Aspect ratio button styles
        self.style.configure("AspectActive.TButton", font=("Segoe UI", 10, "bold"), padding=6,
                             background="#0E639C", foreground="#FFFFFF")
        self.style.map("AspectActive.TButton", background=[("active", "#1177BB")])
        self.style.configure("AspectInactive.TButton", font=("Segoe UI", 10), padding=6,
                             background="#3C3C3C", foreground="#AAAAAA")
        self.style.map("AspectInactive.TButton", background=[("active", "#4A4A4A")])

        self.data_var = tk.StringVar()
        self.batches = {}
        self.prompts = {}
        self.animations = {}
        self.scene_keys = []
        self.current_scene_index = 0
        self.photo_refs = []
        
        self.show_input_page()

    def prepare_scenes(self):
        scenes = []

        for scene_key, prompt in self.prompts.items():
            if not prompt or not str(prompt).strip():
                continue
                
            scene_number = int(scene_key.replace("scene", ""))

            scenes.append({
                "scene": scene_number,
                "prompt": prompt
            })

        return scenes
    
    

    def show_input_page(self):
        self.input_frame = ttk.Frame(self)
        self.input_frame.pack(expand=True, fill="both")
        
        center_frame = ttk.Frame(self.input_frame)
        center_frame.place(relx=0.5, rely=0.5, anchor="center")
        
        ttk.Label(center_frame, text="System Initialization", style="Header.TLabel").pack(pady=(0, 20))
        ttk.Label(center_frame, text="Please enter your authentication/input data:").pack(pady=5)
        
        self.entry_data = ttk.Entry(center_frame, textvariable=self.data_var, width=45, font=("Segoe UI", 12))
        self.entry_data.pack(pady=10)
        
        submit_btn = ttk.Button(center_frame, text="Proceed to Dashboard", command=self.load_main_page)
        submit_btn.pack(pady=20)

    def load_main_page(self):
        input_val = self.data_var.get().strip()
        if not input_val:
            messagebox.showwarning("Input Required", "Data input is required to proceed.")
            return
        
        # PARSE JSON
        try:
            json_data = json.loads(input_val)  
        except json.JSONDecodeError:
            print("Invalid JSON input.")
            exit()

        result = process_scenes(json_data)

        # NOT Optional: save processed result into Text_Files 
        with open("D:\AI_Schemea\Text_Files\processed_output.json", "w", encoding="utf-8") as f:
            json.dump(result, f, indent=2)
            
        print(f"[INFO] Initialized with data: {input_val}")
        
        self.input_frame.destroy()
        self.setup_main_page()
        self.load_data()
        self.display_current_scene()
        
        # Trigger pipeline now that data is loaded
        if self.on_ready_callback:
            self.on_ready_callback(self)

    def setup_main_page(self):
        # Left Sidebar Navigation
        self.sidebar = ttk.Frame(self, style="Sidebar.TFrame", width=250)
        self.sidebar.pack(side="left", fill="y")
        self.sidebar.pack_propagate(False)
        
        ttk.Label(self.sidebar, text="Navigation", style="SidebarHeader.TLabel").pack(pady=(20, 10), padx=15, anchor="w")

        # Tabs
        self.btn_tab_dashboard = ttk.Button(self.sidebar, text="Dashboard Overview", command=self.show_dashboard_view)
        self.btn_tab_dashboard.pack(fill="x", padx=15, pady=5)

        self.btn_tab_image_seq = ttk.Button(self.sidebar, text="Image Sequence Scenes", command=self.show_image_seq_view)
        self.btn_tab_image_seq.pack(fill="x", padx=15, pady=5)
        
        ttk.Label(self.sidebar, text="Stats", style="SidebarHeader.TLabel").pack(pady=(20, 10), padx=15, anchor="w")
        
        self.lbl_total_scenes = ttk.Label(self.sidebar, text="Unique Scenes: 0", style="Sidebar.TLabel")
        self.lbl_total_scenes.pack(pady=5, padx=15, anchor="w")
        
        self.lbl_total_images = ttk.Label(self.sidebar, text="Total Images: 0", style="Sidebar.TLabel")
        self.lbl_total_images.pack(pady=5, padx=15, anchor="w")
        
        # Main Layout container
        self.main_container = ttk.Frame(self)
        self.main_container.pack(side="right", expand=True, fill="both")
        
        # Pages dictionary to hold frames
        self.pages = {}
        
        # --- DASHBOARD PAGE ---
        self.pages["dashboard"] = ttk.Frame(self.main_container)
        
        # Top Navigation
        self.top_nav = ttk.Frame(self.pages["dashboard"])
        self.top_nav.pack(side="top", fill="x", padx=20, pady=20)
        
        self.btn_prev = ttk.Button(self.top_nav, text="◀ Previous Batch", command=self.prev_scene)
        self.btn_prev.pack(side="left")
        
        self.lbl_scene_name = ttk.Label(self.top_nav, text="Current Scene: None", font=("Segoe UI", 16, "bold"), foreground="#FFFFFF")
        self.lbl_scene_name.pack(side="left", expand=True)
        
        self.btn_next = ttk.Button(self.top_nav, text="Next Batch ▶", command=self.next_scene)
        self.btn_next.pack(side="right")
        
        # Prompt Area
        self.prompt_frame = ttk.Frame(self.pages["dashboard"])
        self.prompt_frame.pack(side="top", fill="x", padx=20)
        
        ttk.Label(self.prompt_frame, text="Scene Prompt (Editable):", font=("Segoe UI", 11, "bold")).pack(anchor="w")
        self.txt_prompt = tk.Text(self.prompt_frame, height=2, font=("Segoe UI", 12), bg="#2D2D30", fg="#FFFFFF", insertbackground="#FFFFFF", relief="flat", padx=10, pady=5)
        self.txt_prompt.pack(fill="x", pady=2)
        
        ttk.Label(self.prompt_frame, text="Scene Animation (Editable):", font=("Segoe UI", 11, "bold")).pack(anchor="w")
        self.txt_animation = tk.Text(self.prompt_frame, height=2, font=("Segoe UI", 12), bg="#2D2D30", fg="#FFFFFF", insertbackground="#FFFFFF", relief="flat", padx=10, pady=5)
        self.txt_animation.pack(fill="x", pady=2)
        
        ttk.Label(self.prompt_frame, text="Negative Video Prompt (Editable):", font=("Segoe UI", 11, "bold")).pack(anchor="w")
        self.txt_negative = tk.Text(self.prompt_frame, height=2, font=("Segoe UI", 12), bg="#2D2D30", fg="#FFFFFF", insertbackground="#FFFFFF", relief="flat", padx=10, pady=5)
        self.txt_negative.pack(fill="x", pady=2)
        
        self.btn_save_json = ttk.Button(self.prompt_frame, text="Save Changes to JSON", command=self.save_json)
        self.btn_save_json.pack(anchor="e", pady=5)
        
        # Image Grid Canvas
        self.canvas_container = ttk.Frame(self.pages["dashboard"])
        self.canvas_container.pack(side="top", expand=True, fill="both", padx=20, pady=10)
        
        self.image_canvas = tk.Canvas(self.canvas_container, bg="#1E1E1E", highlightthickness=0)
        self.scrollbar = ttk.Scrollbar(self.canvas_container, orient="vertical", command=self.image_canvas.yview)
        
        self.image_frame = ttk.Frame(self.image_canvas)
        self.image_frame.bind("<Configure>", lambda e: self.image_canvas.configure(scrollregion=self.image_canvas.bbox("all")))
        
        self.image_canvas.bind('<Configure>', lambda e: self.image_canvas.itemconfig('frame', width=self.image_canvas.winfo_width()))
        self.image_canvas.create_window((0, 0), window=self.image_frame, anchor="nw", tags="frame")
        
        self.scrollbar.pack(side="right", fill="y")
        self.image_canvas.pack(side="left", expand=True, fill="both")
        self.image_canvas.configure(yscrollcommand=self.scrollbar.set)
        
        # Mousewheel binding
        def _on_mousewheel(event):
            self.image_canvas.yview_scroll(int(-1*(event.delta/120)), "units")
            
        self.image_canvas.bind('<Enter>', lambda e: self.image_canvas.bind_all("<MouseWheel>", _on_mousewheel))
        self.image_canvas.bind('<Leave>', lambda e: self.image_canvas.unbind_all("<MouseWheel>"))
        
        # Bottom Controls
        self.bottom_frame = ttk.Frame(self.pages["dashboard"])
        self.bottom_frame.pack(side="bottom", fill="x", pady=20, padx=20)
        
        ttk.Button(self.bottom_frame, text="↻ Reload Data", command=self.reload_data).pack(side="left")
        
        ttk.Button(self.bottom_frame, text="Exit Application", style="Danger.TButton", command=self.destroy).pack(side="right", padx=(10, 0))
        ttk.Button(self.bottom_frame, text="▶ Video Process", command=self.video_process).pack(side="right")
        
        # --- IMAGE SEQUENCE SCENES PAGE ---
        self.pages["image_seq"] = ttk.Frame(self.main_container)
        self.setup_image_seq_page()
        
        # Show Dashboard by default
        self.show_dashboard_view()

    def setup_image_seq_page(self):
        self.seq_scenes = []
        self.seq_current_index = 0
        self.seq_selections = {}
        self.historical_images = []
        self.seq_photo_refs = []
        self.dir_historical_photos = os.path.join(BASE_DIR, "historical_photos")

        # Per-scene aspect ratio tracker: { scene_id: "4:3" | "9:16" }
        self.seq_aspect_ratios = {}
        
        # Top Data Area
        top_frame = ttk.Frame(self.pages["image_seq"])
        top_frame.pack(fill="x", pady=20, padx=20)
        
        self.seq_btn_prev = ttk.Button(top_frame, text="◀ Previous Scene", command=self.seq_prev_scene)
        self.seq_btn_prev.pack(side="left")
        
        info_frame = ttk.Frame(top_frame)
        info_frame.pack(side="left", expand=True, fill="both", padx=20)
        
        self.seq_lbl_desc = ttk.Label(info_frame, text="Description: None", font=("Segoe UI", 12, "bold"), wraplength=400)
        self.seq_lbl_desc.grid(row=0, column=0, sticky="w", pady=2)
        
        self.seq_lbl_vo = ttk.Label(info_frame, text="VO: None", font=("Segoe UI", 11, "italic"), wraplength=400)
        self.seq_lbl_vo.grid(row=1, column=0, sticky="w", pady=2)
        
        self.seq_lbl_duration = ttk.Label(info_frame, text="Duration: N/A", font=("Segoe UI", 12, "bold"))
        self.seq_lbl_duration.grid(row=0, column=1, rowspan=2, sticky="e", padx=20)
        
        info_frame.columnconfigure(0, weight=1)

        # ── Aspect Ratio Selector ─────────────────────────────────────────────
        aspect_frame = ttk.Frame(top_frame)
        aspect_frame.pack(side="right", padx=(10, 0))

        ttk.Label(aspect_frame, text="Aspect Ratio:", font=("Segoe UI", 10, "bold"),
                  foreground="#CCCCCC").pack(side="left", padx=(0, 6))

        self.btn_aspect_43 = ttk.Button(
            aspect_frame, text="4:3",
            style="AspectInactive.TButton",
            command=lambda: self.set_aspect_ratio("4:3")
        )
        self.btn_aspect_43.pack(side="left", padx=3)

        self.btn_aspect_916 = ttk.Button(
            aspect_frame, text="9:16",
            style="AspectInactive.TButton",
            command=lambda: self.set_aspect_ratio("9:16")
        )
        self.btn_aspect_916.pack(side="left", padx=3)
        # ─────────────────────────────────────────────────────────────────────

        self.seq_btn_next = ttk.Button(top_frame, text="Next Scene ▶", command=self.seq_next_scene)
        self.seq_btn_next.pack(side="right")
        
        # Image Grid Canvas
        self.seq_canvas_container = ttk.Frame(self.pages["image_seq"])
        self.seq_canvas_container.pack(expand=True, fill="both", padx=20, pady=10)
        
        self.seq_canvas = tk.Canvas(self.seq_canvas_container, bg="#1E1E1E", highlightthickness=0)
        self.seq_scrollbar = ttk.Scrollbar(self.seq_canvas_container, orient="vertical", command=self.seq_canvas.yview)
        self.seq_image_frame = ttk.Frame(self.seq_canvas)
        
        self.seq_image_frame.bind("<Configure>", lambda e: self.seq_canvas.configure(scrollregion=self.seq_canvas.bbox("all")))
        self.seq_canvas.create_window((0, 0), window=self.seq_image_frame, anchor="nw")
        
        self.seq_scrollbar.pack(side="right", fill="y")
        self.seq_canvas.pack(side="left", expand=True, fill="both")
        self.seq_canvas.configure(yscrollcommand=self.seq_scrollbar.set)
        
        # Bottom Layout
        bottom_frame = ttk.Frame(self.pages["image_seq"])
        bottom_frame.pack(side="bottom", fill="x", pady=20, padx=20)
        
        ttk.Button(bottom_frame, text="Load / Refresh Images", command=self.load_image_seq_data).pack(side="left")
        ttk.Button(bottom_frame, text="Finish Selection", style="TButton", command=self.finish_seq_selection).pack(side="right", padx=(10, 0))

        # ── Generate Image Scenes button ──────────────────────────────────────
        ttk.Button(
            bottom_frame,
            text="🖼  Generate Image Scenes",
            style="TButton",
            command=self.trigger_image_sequence_generation
        ).pack(side="right", padx=(10, 0))
        # ─────────────────────────────────────────────────────────────────────

        self.load_image_seq_data()

    # ── Aspect ratio helpers ──────────────────────────────────────────────────

    def set_aspect_ratio(self, ratio: str):
        """Store the selected aspect ratio for the current scene and update button styles."""
        if not self.seq_scenes:
            return

        scene_id = self.seq_scenes[self.seq_current_index].get("scene", "?")
        self.seq_aspect_ratios[scene_id] = ratio

        # Update button appearance to reflect active selection
        self._refresh_aspect_buttons(ratio)

    def _refresh_aspect_buttons(self, active_ratio: str):
        """Visually highlight the active aspect ratio button."""
        if active_ratio == "4:3":
            self.btn_aspect_43.configure(style="AspectActive.TButton")
            self.btn_aspect_916.configure(style="AspectInactive.TButton")
        else:
            self.btn_aspect_43.configure(style="AspectInactive.TButton")
            self.btn_aspect_916.configure(style="AspectActive.TButton")

    # ── Generate Image Scenes trigger ─────────────────────────────────────────

    def trigger_image_sequence_generation(self):
        """Collect duration_seconds for every scene and invoke Image_sequence_generation."""
        if not self.seq_scenes:
            messagebox.showwarning("No Scenes", "No historical photo scenes are loaded.")
            return

        # Build list of (scene_id, duration_seconds) from all loaded scenes
        scene_durations = [
            {
                "scene": s.get("scene"),
                "duration_seconds": s.get("duration_seconds"),
                "aspect_ratio": self.seq_aspect_ratios.get(s.get("scene"), None)
            }
            for s in self.seq_scenes
        ]

        print(f"[INFO] Triggering Image_sequence_generation for {len(scene_durations)} scene(s).")

        threading.Thread(
            target=lambda: Image_sequence_generation(scene_durations),
            daemon=True
        ).start()

    # ─────────────────────────────────────────────────────────────────────────

    def load_image_seq_data(self):
        # Read from Historical Photos dir
        self.historical_images = []
        if os.path.exists(self.dir_historical_photos):
            for file in os.listdir(self.dir_historical_photos):
                if file.lower().endswith(('.png', '.jpg', '.jpeg', '.gif')):
                    self.historical_images.append(os.path.join(self.dir_historical_photos, file))
                    
        # Read from JSON
        self.seq_scenes = []
        if os.path.exists(JSON_FILE):
            try:
                with open(JSON_FILE, 'r', encoding='utf-8') as f:
                    data = json.load(f)
                
                hist_photos = data.get("historical_photos", [])
                for hp in hist_photos:
                    if hp:
                        self.seq_scenes.append(hp)
            except Exception as e:
                print(f"[ERROR] Loading sequence data: {e}")
                
        if self.seq_scenes:
            self.seq_current_index = 0
            self.display_seq_scene()
        else:
            self.seq_lbl_desc.config(text="No historical photo scenes found.")
            for widget in self.seq_image_frame.winfo_children():
                widget.destroy()

    def display_seq_scene(self):
        if not self.seq_scenes:
            return
            
        scene = self.seq_scenes[self.seq_current_index]
        scene_id = scene.get("scene", "?")
        desc = scene.get("photo_description", scene.get("historical_photo_description", "No description"))
        vo = scene.get("vo_line", scene.get("VO_line", "N/A"))
        duration = scene.get("duration_seconds", "N/A")
        
        self.seq_lbl_desc.config(text=f"Scene {scene_id}: {desc}")
        self.seq_lbl_vo.config(text=f"VO: {vo}")
        self.seq_lbl_duration.config(text=f"Duration: {duration}s")

        # Reflect saved aspect ratio for this scene (or reset both to inactive)
        saved_ratio = self.seq_aspect_ratios.get(scene_id)
        if saved_ratio:
            self._refresh_aspect_buttons(saved_ratio)
        else:
            self.btn_aspect_43.configure(style="AspectInactive.TButton")
            self.btn_aspect_916.configure(style="AspectInactive.TButton")
        
        for widget in self.seq_image_frame.winfo_children():
            widget.destroy()
            
        self.seq_photo_refs.clear()
        
        cols = 3
        for idx, img_path in enumerate(self.historical_images):
            row = idx // cols
            col = idx % cols
            
            card = ttk.Frame(self.seq_image_frame, style="Card.TFrame", padding=10)
            is_selected = img_path in self.seq_selections.get(scene_id, [])
            if is_selected:
                card.configure(style="CardSelected.TFrame")
                # Creating custom selected style dynamically if possible or just use a label
                
            card.grid(row=row, column=col, padx=10, pady=10)
            
            try:
                if HAS_PIL:
                    pil_img = Image.open(img_path)
                    pil_img.thumbnail((250, 250), Image.Resampling.LANCZOS)
                    photo = ImageTk.PhotoImage(pil_img)
                    self.seq_photo_refs.append(photo)
                    lbl_img = tk.Label(card, image=photo, bg="#2D2D30")
                else:
                    photo = tk.PhotoImage(file=img_path)
                    self.seq_photo_refs.append(photo)
                    lbl_img = tk.Label(card, image=photo, bg="#2D2D30")
                    
                lbl_img.pack()
                
                # Highlight if selected
                bg_color = "green" if is_selected else ""
                if bg_color: lbl_img.config(bg=bg_color)
                
                btn_text = "Deselect" if is_selected else "Select This"
                btn_sel = ttk.Button(card, text=btn_text, 
                                     command=lambda s=scene_id, p=img_path: self.seq_select_image(s, p))
                btn_sel.pack(pady=5)
            except Exception as e:
                ttk.Label(card, text="Error loading").pack()

    def seq_select_image(self, scene_id, img_path):
        if scene_id not in self.seq_selections:
            self.seq_selections[scene_id] = []
            
        if img_path in self.seq_selections[scene_id]:
            self.seq_selections[scene_id].remove(img_path)
        else:
            self.seq_selections[scene_id].append(img_path)
            
        self.display_seq_scene()

    def seq_prev_scene(self):
        if self.seq_scenes and self.seq_current_index > 0:
            self.seq_current_index -= 1
            self.display_seq_scene()

    def seq_next_scene(self):
        if self.seq_scenes and self.seq_current_index < len(self.seq_scenes) - 1:
            self.seq_current_index += 1
            self.display_seq_scene()

    def finish_seq_selection(self):
        """Save image selections AND per-scene aspect ratios to historical_selections.json."""
        filepath = os.path.join(BASE_DIR, "Text_Files", "historical_selections.json")
        try:
            # Build structured output: per scene, store selected images + aspect ratio
            output = {}
            all_scene_ids = set(list(self.seq_selections.keys()) + list(self.seq_aspect_ratios.keys()))

            for scene_id in all_scene_ids:
                output[scene_id] = {
                    "selected_images": self.seq_selections.get(scene_id, []),
                    "aspect_ratio": self.seq_aspect_ratios.get(scene_id, None)
                }

            with open(filepath, 'w', encoding='utf-8') as f:
                json.dump(output, f, indent=4)

            messagebox.showinfo("Success", f"Selections saved to {filepath}")
        except Exception as e:
            messagebox.showerror("Error", f"Failed to save selections: {e}")

    def show_dashboard_view(self):
        for frame in self.pages.values():
            frame.pack_forget()
        self.pages["dashboard"].pack(expand=True, fill="both")

    def show_image_seq_view(self):
        for frame in self.pages.values():
            frame.pack_forget()
        self.pages["image_seq"].pack(expand=True, fill="both")

    def save_json(self):
        if not self.scene_keys:
            return
            
        scene_key = self.scene_keys[self.current_scene_index]
        new_prompt = self.txt_prompt.get("1.0", tk.END).strip()
        new_animation = self.txt_animation.get("1.0", tk.END).strip()
        new_negative = self.txt_negative.get("1.0", tk.END).strip()
        
        self.prompts[scene_key] = new_prompt
        self.animations[scene_key] = new_animation
        self.negative_prompts[scene_key] = new_negative
        
        if os.path.exists(JSON_FILE):
            try:
                with open(JSON_FILE, 'r', encoding='utf-8') as f:
                    data = json.load(f)
                
                scene_number = int(scene_key.replace("scene", ""))
                
                for item in data.get('scene_visuals', []):
                    if str(item.get('scene', '')) == str(scene_number):
                        item['primary_visual_image'] = new_prompt
                        
                for item in data.get('scene_animations', []):
                    if str(item.get('scene', '')) == str(scene_number):
                        item['animation'] = new_animation
                        item['negative_video_prompt'] = new_negative
                        
                with open(JSON_FILE, 'w', encoding='utf-8') as f:
                    json.dump(data, f, indent=2)
                    
                messagebox.showinfo("Success", "JSON file successfully updated!")
            except Exception as e:
                messagebox.showerror("Error", f"Failed to update JSON: {e}")
        else:
            messagebox.showerror("Error", "JSON file not found.")

    def reload_data(self):
        self.load_data()
        self.display_current_scene()

    def load_data(self):
        self.batches = {}
        self.prompts = {}
        self.animations = {}
        self.negative_prompts = {}
        total_images = 0
        
        if os.path.exists(IMAGE_DIR):
            for file in os.listdir(IMAGE_DIR):
                if file.lower().endswith(('.png', '.jpg', '.jpeg')):
                    parts = file.split('_')
                    if len(parts) > 0:
                        scene_prefix = parts[0]
                        if scene_prefix not in self.batches:
                            self.batches[scene_prefix] = []
                        self.batches[scene_prefix].append(os.path.join(IMAGE_DIR, file))
                        total_images += 1
                        
        for scene in self.batches:
            self.batches[scene].sort()
            
        if os.path.exists(JSON_FILE):
            try:
                with open(JSON_FILE, 'r', encoding='utf-8') as f:
                    data = json.load(f)
                
                # Try to map prompts using common structures
                for item in data.get('scene_visuals', []):
                    scene_id = f"scene{item.get('scene', '')}"
                    self.prompts[scene_id] = item.get('primary_visual_image') or ""
                for item in data.get('scene_animations', []):
                    scene_id = f"scene{item.get('scene', '')}"
                    self.animations[scene_id] = item.get('animation', "")
                    self.negative_prompts[scene_id] = item.get('negative_video_prompt', "")
            except Exception as e:
                print(f"[ERROR] Loading JSON: {e}")
                
        self.scene_keys = sorted(list(self.batches.keys()))
        self.lbl_total_scenes.config(text=f"Unique Scenes: {len(self.scene_keys)}")
        self.lbl_total_images.config(text=f"Total Images: {total_images}")
        
        if not self.scene_keys:
            self.lbl_scene_name.config(text="No Scenes Available")

    def display_current_scene(self):
        for widget in self.image_frame.winfo_children():
            widget.destroy()
            
        self.photo_refs.clear()
        
        if not self.scene_keys:
            ttk.Label(self.image_frame, text="No images found in directory.", font=("Segoe UI", 12)).pack(pady=20)
            return
            
        scene_key = self.scene_keys[self.current_scene_index]
        self.lbl_scene_name.config(text=f"Scene: {scene_key.upper()}  ({self.current_scene_index + 1} of {len(self.scene_keys)})")
        
        self.txt_prompt.delete("1.0", tk.END)
        prompt_text = self.prompts.get(scene_key, "No prompt available for this scene.")
        if prompt_text is None:
            prompt_text = "No prompt available for this scene."
        elif not isinstance(prompt_text, str):
            prompt_text = str(prompt_text)
        self.txt_prompt.insert(tk.END, prompt_text)
        
        self.txt_animation.delete("1.0", tk.END)
        animation_text = self.animations.get(scene_key, "No animation available for this scene.")
        if animation_text is None:
            animation_text = "No animation available for this scene."
        elif not isinstance(animation_text, str):
            animation_text = str(animation_text)
        self.txt_animation.insert(tk.END, animation_text)
        
        self.txt_negative.delete("1.0", tk.END)
        negative_text = self.negative_prompts.get(scene_key, "")
        if negative_text is None:
            negative_text = ""
        elif not isinstance(negative_text, str):
            negative_text = str(negative_text)
        self.txt_negative.insert(tk.END, negative_text)
        
        images = self.batches.get(scene_key, [])
        cols = 2
        
        for idx, img_path in enumerate(images):
            row = idx // cols
            col = idx % cols
            
            card = ttk.Frame(self.image_frame, style="Card.TFrame", padding=15)
            card.grid(row=row, column=col, padx=10, pady=10, sticky="nsew")
            
            try:
                if HAS_PIL:
                    pil_img = Image.open(img_path)
                    # Resize while keeping aspect ratio
                    pil_img.thumbnail((450, 350), Image.Resampling.LANCZOS)
                    photo = ImageTk.PhotoImage(pil_img)
                    self.photo_refs.append(photo)
                    lbl_img = tk.Label(card, image=photo, bg="#2D2D30")
                else:
                    # Fallback to tk.PhotoImage if PIL is missing, scaling only works for subsets
                    photo = tk.PhotoImage(file=img_path)
                    self.photo_refs.append(photo)
                    lbl_img = tk.Label(card, image=photo, bg="#2D2D30")
                
                lbl_img.pack(pady=(0, 10))
                
                btn_frame = ttk.Frame(card)
                btn_frame.pack(fill="x")
                
                # Delete Rest Button
                btn_keep = ttk.Button(btn_frame, text="Keep & Delete Rest", 
                                      command=lambda p=img_path, s=scene_key: self.keep_one_delete_rest(s, p))
                btn_keep.pack(side="left", expand=True, padx=5)
                
                # Regenerate Button
                btn_regen = ttk.Button(btn_frame, text="Edit Prompt & Regen", 
                                       command=lambda p=img_path: self.regenerate_image(p))
                btn_regen.pack(side="right", expand=True, padx=5)
                
            except Exception as e:
                lbl_err = ttk.Label(card, text=f"[Image Loading Error]\n{os.path.basename(img_path)}")
                lbl_err.pack(pady=20)

    def keep_one_delete_rest(self, scene_key, keep_path):
        if messagebox.askyesno("Confirm Deletion", "This will delete all other images in this batch permanently. Proceed?"):
            images = self.batches.get(scene_key, [])
            for img_path in images:
                if img_path != keep_path:
                    try:
                        os.remove(img_path)
                        print(f"[REMOVED] {img_path}")
                    except Exception as e:
                        print(f"[WARN] Failed to remove {img_path}: {e}")
            self.reload_data()

    def regenerate_image(self, target_img_path):
        new_prompt = self.txt_prompt.get("1.0", tk.END).strip()
        messagebox.showinfo("Regeneration Triggered", 
                           f"Processing Regeneration for:\n{target_img_path}\n\nUsing Prompt:\n{new_prompt}")
        
        Image_prompts_regen=[]

        scene_key = self.scene_keys[self.current_scene_index]
        scene_number = int(scene_key.replace("scene", ""))

        Image_prompts_regen.append({
            "scene": scene_number,
            "prompt": new_prompt
        })
        
        print(f"[REGENERATE] File: {target_img_path} | Prompt: {new_prompt}")
        threading.Thread(
            target=lambda: asyncio.run(Image_pipeline(Image_prompts_regen)),
            daemon=True
        ).start()

    def video_process(self):
        messagebox.showinfo("Video Process", "Initiating Video Processing pipeline for all batches...")
        print("[PROCESS] Video Process Initiated.")
        
        video_jobs = []
        for scene_key, paths in self.batches.items():
            # Skip pipeline for scene if animation is null/empty
            anim = self.animations.get(scene_key)
            neg = self.negative_prompts.get(scene_key, "")
            
            if not anim or not str(anim).strip():
                print(f"[PROCESS] Skipping video generation for {scene_key} (animation is null/empty).")
                continue
                
            for p in paths:
                video_jobs.append({
                    "path": p,
                    "positive_prompt": anim,
                    "negative_prompt": neg
                })
            
        print(f"[PROCESS] Found {len(video_jobs)} images to process for video.")
        
        threading.Thread(
            target=lambda: asyncio.run(Video_pipeline(video_jobs)),
            daemon=True
        ).start()

    def prev_scene(self):
        if self.scene_keys:
            self.current_scene_index = (self.current_scene_index - 1) % len(self.scene_keys)
            self.display_current_scene()

    def next_scene(self):
        if self.scene_keys:
            self.current_scene_index = (self.current_scene_index + 1) % len(self.scene_keys)
            self.display_current_scene()





async def Image_pipeline(scenes: list) -> None:
    """
    Full pipeline:
      - Generate image(s)
      - For every output image, launch a video gen job concurrently
    """
    from MAIN_AI_PIPELINE import run_Flux_Image_Gen


    with ThreadPoolExecutor(max_workers=MAX_WORKERS) as executor:


        # Launch image generation for every prompt
        image_tasks = [
            asyncio.create_task(run_Flux_Image_Gen(scene, executor))
            for scene in scenes   # EACH scene is a dict
        ]

        image_results = await asyncio.gather(*image_tasks)

        # Flatten list (because each prompt returns a list of image paths)
        image_paths = []
        for result in image_results:
            image_paths.extend(result)

        print(f"[MAIN] ✔ Generated {len(image_paths)} image(s)")

async def Video_pipeline(video_jobs: list) -> None:
    """
    Full pipeline:
      - Generate video(s)
      - For every output image, launch a video gen job concurrently
    """
    from MAIN_AI_PIPELINE import run_WAN_I2V_Gen

    with ThreadPoolExecutor(max_workers=MAX_WORKERS) as executor:

        # Launch Video generation for every image path
        video_tasks = [
            asyncio.create_task(run_WAN_I2V_Gen(job["path"], job["positive_prompt"], job["negative_prompt"], executor))
            for job in video_jobs
        ]

        Video_results = await asyncio.gather(*video_tasks)

        # Flatten list
        generated_videos = []
        for result in Video_results:
            if isinstance(result, list):
                generated_videos.extend(result)
            elif result:
                generated_videos.append(result)

        print(f"[MAIN] ✔ Generated {len(generated_videos)} Video(s)")

# if __name__ == "__main__":
    # app = CorporateUIApp()
    # app.mainloop()